language: ruby
rvm:
  - 1.8.7

script:
  #- "ln -s manifests/moco-config.pp manifests/config.pp"
  #- "ln -s manifests/moco-nodes.pp manifests/nodes.pp"
  # Added manifests directory to validate. I skiped site.pp from check, to prevent errors related missing links 
  # for config.pp and nodes.pp
  - "puppet parser validate `find manifests modules -name '*.pp' -not -name 'site.pp'`"
  # Skipping from the lint check all modules that are imported from puppet labs. These modules are:
  # acl, assert, concat, firewall, java_ks, powershell, registry, stdlib, windows_firewall and windows_path
  # Checked also for lint the pp files located into manifests directory
  - "puppet-lint \
      --no-140chars-check \
      --no-case_without_default-check \
      --no-only_variable_string-check \
      --no-unquoted_file_mode-check \
      --no-nested_classes_or_defines \
      --no-quoted_booleans \
      --no-puppet_url_without_modules \
      --no-selector_inside_resource \
      --no-file_mode-check \
      --no-variable_scope-check \
      --no-arrow_on_right_operand_line \
      --no-double_quoted_strings-check \
      --no-autoloader_layout-check \
      --fail-on-warnings \
      --log-format '%{path} - %{KIND}: %{message} on line %{line} - %{check}' \
      `find manifests modules -name '*.pp' \
       -not -path 'modules/acl/*' \
       -not -path 'modules/assert/*' \
       -not -path 'modules/concat/*' \
       -not -path 'modules/firewall/*' \
       -not -path 'modules/java_ks/*' \
       -not -path 'modules/powershell/*' \
       -not -path 'modules/registry/*' \
       -not -path 'modules/stdlib/*' \
       -not -path 'modules/windows_firewall/*' \
       -not -path 'modules/windows_path/*'`"
gemfile: .gemfile

before_install: gem install bundler -v1.17.3

# The channel name "irc.mozilla.org#releng-bots" is encrypted against mozilla-releng/build-puppet to prevent IRC spam of forks
# Generated with: travis encrypt --repo mozilla-releng/build-puppet --skip-version-check irc.mozilla.org#releng-bots
notifications:
  irc:
    channels:
      - secure: "BThC3WlKQ0KLhJyRH7L/6StvdTFKMU1cXhTG4wpO04iz8pSHSUNb13L9CZeFrva35bOd6HMEa7VHkPkmvftI3OR04pY75eemzXR6KQy3IeyZGFbiexrayegYFc63yFTTp+09lK9GAHQQ1rTxFCPEOwlQXaWcWptstuMvv56rWSQ="
    on_success: always
    on_failure: always
    template:
      - "\x02%{repository_name}\x0314#%{build_number}\x03\x02 (%{branch} - %{commit} : %{author}): \x02\x0312%{message}\x02\x03 (\x0314%{build_url}\x03)"
